#!/bin/bash
set -e
{
unamestr=$(uname)
scriptDir=$(dirname "$0")
mkdir -p ${scriptDir}/working/.

if [[ "$unamestr" == 'Linux' ]]; then
    scriptDir=$(readlink -f "$scriptDir")
elif [[ "$unamestr" == 'Darwin' ]]; then
    scriptDir=$(greadlink -f "$scriptDir")
fi
} &> /dev/null

if [[ $(git diff --stat) != '' ]]; then
  echo 'Uncommited changes, please commit first.'
  exit
fi

bump2version --allow-dirty patch build_ant/setup.py xenon_view_sdk/__init__.py
